apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
  Namespace: sentiment
  labels:
    app: sa-feedback
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
